name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - develop
  pull_request:

jobs:
  build_application:
    name: Build application using Ledger's reusable workflow
    uses: LedgerHQ/ledger-app-workflows/.github/workflows/reusable_build.yml@v1
    with:
      upload_app_binaries_artifact: compiled_app_binaries
  
  scan_build:
    name: Perform static analysis using Ledger's reusable workflow
    uses: LedgerHQ/ledger-app-workflows/.github/workflows/_check_clang_static_analyzer.yml@v1
  
  ragger_tests:
    name: Functional tests with Ragger
    needs: build_application
    strategy:
      fail-fast: false
      matrix:
        include:
          - device: nanos
          - device: nanox
          - device: nanosp
          - device: stax
    runs-on: ubuntu-latest
    steps:
      - name: Clone
        uses: actions/checkout@v3
      - name: Download app binaries
        uses: actions/download-artifact@v3
        with:
          name: compiled_app_binaries
          path: build
      - name: Install tests dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y qemu-user-static tesseract-ocr libtesseract-dev
          pip install --upgrade pip
          pip install --extra-index-url https://test.pypi.org/simple/ -r requirements.txt
      - name: Build proto
        run: |
          cd examples
          ./buildproto.sh  
      - name: Run test
        env:
          CTEST_OUTPUT_ON_FAILURE: 1
        run: |
          pytest tests --tb=short -v --device ${{ matrix.device }}
