name: Swap functional tests

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - main
      - develop
  pull_request:

jobs:
  job_functional_tests:
    uses: LedgerHQ/app-exchange/.github/workflows/reusable_swap_functional_tests.yml@develop
    with:
      branch_for_tron: ${{ github.ref }}
      test_filter: '"TRX or trx or Tron or tron"'
